# Generated by Django 4.2.22 on 2025-06-09 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_product_is_active_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Короткая метка для контента, содержащая только буквы, цифры, подчеркивания (_) или дефисы (-)', unique=True, verbose_name='Уникальный URL'),
        ),
    ]
