# Generated by Django 4.2.22 on 2025-06-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
