# Generated by Django 4.2.22 on 2025-06-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Короткая метка для контента, содержащая только буквы, цифры, подчеркивания (_) или дефисы (-)', null=True, unique=True, verbose_name='Уникальный URL'),
        ),
    ]
