# Generated by Django 4.2.22 on 2025-07-04 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка(от 0 до 100), %'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Подтверждено'), ('canceled', 'Отменено'), ('pending', 'В обработке')], default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
