# Generated by Django 4.2.22 on 2025-07-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_remove_order_price_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
