# Generated by Django 4.2.22 on 2025-07-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_remove_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Подтвержден'), ('canceled', 'Отменен'), ('pending', 'В обработке')], default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
