# Generated by Django 4.2.22 on 2025-07-07 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_cartitem_options_cartitem_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-id'], 'verbose_name': 'предмет корзины', 'verbose_name_plural': 'Предметы корзины'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='address_apartment',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2000)], verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_building',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(300)], verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_floor',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_street',
            field=models.CharField(default='', max_length=100, verbose_name='Улица'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона (например, +375 12 345 67 89)', regex='^[\\d+]\\d+$'), django.core.validators.MinLengthValidator(10)], verbose_name='Телефон'),
        ),
    ]
