# Generated by Django 4.2.22 on 2025-07-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_alter_cartitem_options_remove_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='_total_price',
            field=models.IntegerField(db_column='Итоговая цена', default=0),
            preserve_default=False,
        ),
    ]
