# Generated by Django 4.2.22 on 2025-07-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_order__total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='_total_price',
        ),
    ]
